/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#f59e0b',
        'on-primary': '#05080e',
        'primary-container': '#332204',
        'on-primary-container': '#fef3c7',
        'primary-fixed': '#fef3c7',
        'primary-fixed-dim': '#fde68a',
        'on-primary-fixed': '#451a03',
        'on-primary-fixed-variant': '#78350f',

        secondary: '#10b981',
        'on-secondary': '#05080e',
        'secondary-container': '#064e3b',
        'on-secondary-container': '#a7f3d0',
        'secondary-fixed': '#d1fae5',
        'secondary-fixed-dim': '#a7f3d0',
        'on-secondary-fixed': '#064e3b',
        'on-secondary-fixed-variant': '#047857',

        tertiary: '#06b6d4',
        'on-tertiary': '#05080e',
        'tertiary-container': '#164e63',
        'on-tertiary-container': '#cffaff',
        'tertiary-fixed': '#cffaff',
        'tertiary-fixed-dim': '#a5f3fc',
        'on-tertiary-fixed': '#083344',
        'on-tertiary-fixed-variant': '#0e7490',

        background: '#05080e',
        'on-background': '#f8fafc',

        surface: '#080d17',
        'on-surface': '#f1f5f9',
        'on-surface-variant': '#94a3b8',
        'surface-variant': '#0f172a',
        'surface-bright': '#0c1322',
        'surface-dim': '#05080e',
        'surface-tint': '#f59e0b',

        'surface-container-lowest': '#080c14',
        'surface-container-low': '#0b1220',
        'surface-container': '#0e172a',
        'surface-container-high': '#121d34',
        'surface-container-highest': '#172642',

        outline: '#334155',
        'outline-variant': '#1e293b',
        'inverse-surface': '#f8fafc',
        'inverse-on-surface': '#0f172a',
        'inverse-primary': '#f59e0b',

        error: '#ef4444',
        'on-error': '#ffffff',
        'error-container': '#7f1d1d',
        'on-error-container': '#fecaca',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'stack-gap': '12px',
        'sidebar-collapsed': '64px',
        'sidebar-width': '280px',
        gutter: '24px',
        'section-gap': '40px',
        'margin-mobile': '16px',
        'container-max': '1200px',
      },
      fontFamily: {
        serif: ['"Playfair Display"', 'Georgia', 'serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'section-header': ['Inter', 'sans-serif'],
        'body-base': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-xs': ['Inter', 'sans-serif'],
        'material-symbols': ['"Material Symbols Outlined"'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'section-header': ['18px', { lineHeight: '28px', fontWeight: '600' }],
        'body-base': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-xs': ['12px', { lineHeight: '18px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
