/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'inverse-primary': '#c0c1ff',
        'tertiary-fixed-dim': '#ffb59d',
        'primary-fixed': '#e1e0ff',
        'tertiary-container': '#932c00',
        'error-container': '#ffdad6',
        primary: '#1713b8',
        surface: '#fbf8ff',
        tertiary: '#6c1e00',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#ffdbd0',
        'secondary-fixed-dim': '#bdc7de',
        'surface-container-lowest': '#ffffff',
        'on-background': '#1b1b23',
        error: '#ba1a1a',
        'on-primary-container': '#bbbdff',
        'secondary-container': '#d6e0f8',
        'on-error': '#ffffff',
        'surface-container-high': '#e9e6f3',
        background: '#fbf8ff',
        'on-primary-fixed-variant': '#2a2bc4',
        'on-surface-variant': '#454555',
        'on-primary-fixed': '#04006d',
        'on-surface': '#1b1b23',
        'primary-fixed-dim': '#c0c1ff',
        'outline-variant': '#c6c5d7',
        'on-secondary-container': '#596377',
        outline: '#767586',
        secondary: '#555f73',
        'surface-container-highest': '#e4e1ed',
        'surface-variant': '#e4e1ed',
        'surface-bright': '#fbf8ff',
        'on-error-container': '#93000a',
        'primary-container': '#3538cd',
        'surface-dim': '#dbd8e5',
        'on-tertiary-fixed': '#390c00',
        'inverse-on-surface': '#f2effc',
        'on-tertiary-container': '#ffaf95',
        'on-primary': '#ffffff',
        'surface-tint': '#4549dc',
        'on-secondary-fixed': '#111c2d',
        'surface-container': '#efecf9',
        'inverse-surface': '#303039',
        'on-tertiary-fixed-variant': '#832600',
        'on-secondary-fixed-variant': '#3d475a',
        'secondary-fixed': '#d9e3fb',
        'surface-container-low': '#f5f2fe',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'stack-gap': '12px',
        'sidebar-collapsed': '64px',
        'sidebar-width': '280px',
        gutter: '24px',
        'section-gap': '40px',
        'margin-mobile': '16px',
        'container-max': '1200px',
      },
      fontFamily: {
        'display-lg': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'section-header': ['Inter', 'sans-serif'],
        'body-base': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-xs': ['Inter', 'sans-serif'],
        'material-symbols': ['"Material Symbols Outlined"'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'section-header': ['18px', { lineHeight: '28px', fontWeight: '600' }],
        'body-base': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-xs': ['12px', { lineHeight: '18px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
